[package]
name = "klefki"
version = "0.1.0"
authors = ["Ryan.K <ryankung@ieee.org>"]
edition = "2018"

[dependencies]
num-bigint = "0.3.1"
num = "0.3.1"
#klefki_derive = { path = "./klefki_derive" }

[dev-dependencies]
rand = "0.8.3"